--Ques 1: Coffee Consumer Count
SELECT
	CITY_ID,
	CITY_NAME,
	(0.4 * CITY.POPULATIONS) AS EST_CONSUMER_PER_CITY
FROM
	CITY
ORDER BY
	3 DESC;

--Ques 2: Total revenue across cities in last quarter of 2023
SELECT
	CITY.CITY_NAME,
	SUM(SALES.TOTAL) AS TOTAL_REVENUE
FROM
	SALES
	JOIN CUSTOMER ON SALES.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
	JOIN CITY ON CUSTOMER.CITY_ID = CITY.CITY_ID
WHERE
	DATE_PART('year', SALES.SALE_DATE) = 2023
	AND DATE_PART('quarter', SALES.SALE_DATE) = 4
GROUP BY
	CITY.CITY_NAME
ORDER BY
	2 DESC;

--where YEAR(sales.sale_date)=2023 and quarter(sales.sale_date)=4;  mysql
--Ques 3: Sales count foreach product
SELECT
	PRODUCT.PRODUCT_ID,
	PRODUCT.PRODUCT_NAME,
	COUNT(SALES.SALE_ID)
FROM
	SALES
	JOIN PRODUCT ON SALES.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY
	PRODUCT.PRODUCT_ID
ORDER BY
	3 DESC;

--Ques 4: Avg Sales amount per city
SELECT
	CITY.CITY_ID,
	CITY.CITY_NAME,
	SUM(SALES.TOTAL) AS TOTAL_REVENUE,
	COUNT(SALES.CUSTOMER_ID) AS TOTAL_CUSTOMER,
	ROUND(
		(
			SUM(SALES.TOTAL)::NUMERIC / COUNT(SALES.CUSTOMER_ID)::NUMERIC
		),
		2
	) AS AVG_SALE
FROM
	SALES
	JOIN CUSTOMER ON SALES.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
	JOIN CITY ON CUSTOMER.CITY_ID = CITY.CITY_ID
GROUP BY
	1
ORDER BY
	3 DESC;

--QUES 5:List of cities along with their populations and estimated coffee consumers
SELECT
	CITY.CITY_ID,
	CITY.CITY_NAME,
	CITY.POPULATIONS,
	ROUND((CITY.POPULATIONS * 0.25), 2) AS EST_CUSTOMERS,
	COUNT(DISTINCT (CUSTOMER.CUSTOMER_ID)) AS UNIQUE_CUSTOMER
FROM
	CITY
	JOIN CUSTOMER ON CITY.CITY_ID = CUSTOMER.CITY_ID
GROUP BY
	1
ORDER BY
	5 DESC;

--QUES 6: TOP 3 SELLING COFFEE PRODUCTS PER CITY BASED ON SALES
SELECT
	CITY.CITY_NAME,
	PRODUCT.PRODUCT_NAME,
	COUNT(SALES.SALE_ID) AS TOTAL_SALE,
	DENSE_RANK() OVER (
		PARTITION BY
			CITY.CITY_NAME
		ORDER BY
			COUNT(SALES.SALE_ID) DESC
	) AS RANK
FROM
	SALES
	JOIN CUSTOMER ON SALES.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
	JOIN PRODUCT ON PRODUCT.PRODUCT_ID = SALES.PRODUCT_ID
	JOIN CITY ON CITY.CITY_ID = CUSTOMER.CITY_ID
GROUP BY
	CITY.CITY_NAME,
	PRODUCT.PRODUCT_NAME;

--QUES 7: UNIQUE CUSTOMERS IN EACH CITY PURCHASING COFFEE PRODUCTS
SELECT
	CITY.CITY_ID,
	CITY.CITY_NAME,
	COUNT((CUSTOMER.CUSTOMER_ID)) AS UNIQUE_CUSTOMER
FROM
	CITY
	JOIN CUSTOMER ON CUSTOMER.CITY_ID = CITY.CITY_ID
	JOIN SALES ON SALES.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
	JOIN PRODUCT ON PRODUCT.PRODUCT_ID = SALES.PRODUCT_ID
WHERE
	PRODUCT.PRODUCT_ID <= 14
GROUP BY
	1
ORDER BY
	3 DESC;

--QUES 8 : EACH CITY AND AVG SALE PER CUSTOMER AND AVGRENT PER CUSTOMER
WITH
	TABLEONE AS (
		SELECT
			CITY.CITY_ID,
			CITY.CITY_NAME,
			CITY.ESTIMATED_RENT,
			SUM(SALES.TOTAL) AS TOTAL_REVENUE,
			COUNT(SALES.CUSTOMER_ID) AS TOTAL_CUSTOMER
		FROM
			SALES
			JOIN CUSTOMER ON SALES.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
			JOIN CITY ON CUSTOMER.CITY_ID = CITY.CITY_ID
		GROUP BY
			1,
			2
	)
SELECT
	*,
	ROUND(ESTIMATED_RENT::INTEGER / TOTAL_CUSTOMER) AS AVG_RENT,
	ROUND((TOTAL_REVENUE::NUMERIC / TOTAL_CUSTOMER), 2) AS AVG_SALE
FROM
	TABLEONE;

--QUES 9: MONTHLY SALES GROWTH
WITH
	CURRENTTABLE AS (
		SELECT
			CITY.CITY_NAME,
			EXTRACT(
				MONTH
				FROM
					SALES.SALE_DATE
			) AS CURRENT_MONTH,
			EXTRACT(
				YEAR
				FROM
					SALES.SALE_DATE
			) AS CURRENT_YEAR,
			SUM(SALES.TOTAL) AS TOTAL_SALE
		FROM
			SALES
			JOIN CUSTOMER ON SALES.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
			JOIN CITY ON CITY.CITY_ID = CUSTOMER.CITY_ID
		GROUP BY
			1,
			2,
			3
		ORDER BY
			1,
			3,
			2
	),
	PREVTABLE AS (
		SELECT
			CITY_NAME,
			CURRENT_MONTH,
			CURRENT_YEAR,
			TOTAL_SALE,
			LAG(TOTAL_SALE, 1) OVER (
				PARTITION BY
					CITY_NAME
				ORDER BY
					CURRENT_YEAR,
					CURRENT_MONTH
			) AS LAST_MONTHSALE
		FROM
			CURRENTTABLE
	)
SELECT
	CITY_NAME,
	CURRENT_YEAR,
	CURRENT_MONTH,
	TOTAL_SALE,
	LAST_MONTHSALE,
	ROUND(
		(TOTAL_SALE - LAST_MONTHSALE)::NUMERIC / LAST_MONTHSALE::NUMERIC * 100,
		2
	) AS GROWTH_RATIO
FROM
	PREVTABLE
WHERE
	LAST_MONTHSALE IS NOT NULL;

--QUES 10: Final Suggestion:- top 3 based on highest sale
SELECT
	CITY.CITY_ID,
	CITY.CITY_NAME,
	CITY.ESTIMATED_RENT,
	SUM(SALES.TOTAL) AS TOTAL_REVENUE,
	COUNT(SALES.CUSTOMER_ID) AS TOTAL_CUSTOMER,
	(0.4 * CITY.POPULATIONS) AS EST_CONSUMER_PER_CITY,
	ROUND(
		CITY.ESTIMATED_RENT::INTEGER / COUNT(SALES.CUSTOMER_ID)
	) AS AVG_RENT,
	ROUND(
		SUM(SALES.TOTAL)::NUMERIC / COUNT(SALES.CUSTOMER_ID),
		2
	) AS AVG_SALE
FROM
	SALES
	JOIN CUSTOMER ON SALES.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
	JOIN CITY ON CUSTOMER.CITY_ID = CITY.CITY_ID
GROUP BY
	1,
	2
ORDER BY
	7,
	8 DESC;